[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.6" }
selene = { source = "Kampfkarren/selene", version = "0.20.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.13.1" }
rbx-aged-cli = { source = "Roblox/rbx-aged-tool", version = "5.x.x" }
