[tools]
rotrieve = { source = "roblox/rotriever", version = "0.5.6" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.20.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "0.13.0" }
rbx-aged-cli = { source = "Roblox/rbx-aged-tool", version = "5.x.x" }
