site_name: Symbol Documentation
site_url: https://roblox.github.io/symbol-lua/
repo_name: Roblox/symbol-lua
repo_url: https://github.com/Roblox/symbol-lua

theme:
  name: material
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'

pages:
  - Home: index.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences