[package]
name = "Symbol"
authors = ["Roblox"]
version = "1.0.0"
content_root = "src"
license = "MIT"
files = ["*", "!**/__tests__", "!jest.config.lua"]

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@3.0.0"
Jest = "github.com/roblox/jest-roblox@3.0.0"
