[package]
name = "Symbol"
authors = ["Roblox"]
version = "0.1.0"
# Specifies the path to the source code for this package
content_root = "src"
# Specifies the license associated with this code
license = "MIT"
# Filters files to be delivered when using this project as a dependency
files = ["*", "!**/__tests__"]

[dependencies]
# Add dependencies here. Dependencies might look like:
# React = "github.com/roblox/roact-alignment@17.0.1-rc.16"

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@3.0.0"
Jest = "github.com/roblox/jest-roblox@3.0.0"
